### ISSUE TITLE
Getting weird errors.

### ISSUE THREAD

**Issue by abhishekdeshkar** [spumer/source-query-proxy#20]
```
2020-03-31 22:06:18,087 [INFO] [sqproxy] eBPF redirection disabled
2020-03-31 22:06:18,088 [DEBUG] [MyLittleServer] Binding ...
2020-03-31 22:06:18,093 [DEBUG] [MyLittleServer] Binding ... done!
2020-03-31 22:06:18,093 [DEBUG] [MyLittleServer] Listening started!
2020-03-31 22:06:18,095 [DEBUG] [MyLittleServer.update-info] Connected to ('10.0.0.4', 27015) (client port=46035)
2020-03-31 22:06:18,096 [DEBUG] [MyLittleServer.update-players] Connected to ('10.0.0.4', 27015) (client port=42334)
2020-03-31 22:06:18,097 [DEBUG] [MyLittleServer.update-rules] Connected to ('10.0.0.4', 27015) (client port=52605)
2020-03-31 22:06:18,098 [DEBUG] [MyLittleServer] Got InfoResponse for 0.002776733999780845s
2020-03-31 22:06:18,098 [DEBUG] [MyLittleServer] Got GetChallengeResponse for 0.0017448230009904364s
2020-03-31 22:06:18,098 [DEBUG] [MyLittleServer] Got GetChallengeResponse for 0.0008056959995883517s
2020-03-31 22:06:18,099 [DEBUG] [MyLittleServer] Got PlayersResponse for 0.0004352289997768821s
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 128, in validate
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqproxy", line 11, in <module>
    sys.exit(sqproxy())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/cli.py", line 14, in run
    run()
  File "/usr/local/lib/python3.7/dist-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/__main__.py", line 19, in run
    asyncio.run(_run_servers())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/__main__.py", line 38, in _run_servers
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 228, in run
    await asyncio.gather(self.update_server_query_cache(), self.listen_client_requests())
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 93, in update_server_query_cache
    self.retry_TimeoutError(self._update_rules)(),
  File "/usr/local/lib/python3.7/dist-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 174, in _update_rules
    client, request, timeout=connection_lifetime,
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 120, in send_recv_packet
    message, data, addr = await client.recv_packet()
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/transport.py", line 178, in recv_packet
    message = self.decode_response(data)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/transport.py", line 169, in decode_response
    return self._decode(packet, msg_classes=self.response_message_classes)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/transport.py", line 123, in _decode
    header = messages.Header.decode(packet)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 31, in wrap
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 460, in decode
    values[field.name], buffer = field.decode(buffer, values)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 74, in needs_buffer
    return func(self, buffer, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 167, in decode
    return (self.validate(struct.unpack(self.format, field_data)[0]), left_overs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 130, in validate
    raise BrokenMessageError("Invalid value ({}) for field '{}'".format(value, self.name))
source_query_proxy.source.messages.BrokenMessageError: Invalid value (1918857325) for field 'split'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 128, in validate
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqproxy", line 11, in <module>
    sys.exit(sqproxy())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/cli.py", line 14, in run
    run()
  File "/usr/local/lib/python3.7/dist-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/__main__.py", line 19, in run
    asyncio.run(_run_servers())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/__main__.py", line 38, in _run_servers
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 228, in run
    await asyncio.gather(self.update_server_query_cache(), self.listen_client_requests())
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 93, in update_server_query_cache
    self.retry_TimeoutError(self._update_rules)(),
  File "/usr/local/lib/python3.7/dist-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 174, in _update_rules
    client, request, timeout=connection_lifetime,
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/proxy.py", line 120, in send_recv_packet
    message, data, addr = await client.recv_packet()
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/transport.py", line 178, in recv_packet
    message = self.decode_response(data)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/transport.py", line 169, in decode_response
    return self._decode(packet, msg_classes=self.response_message_classes)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/transport.py", line 123, in _decode
    header = messages.Header.decode(packet)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 31, in wrap
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 460, in decode
    values[field.name], buffer = field.decode(buffer, values)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 74, in needs_buffer
    return func(self, buffer, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 167, in decode
    return (self.validate(struct.unpack(self.format, field_data)[0]), left_overs)
  File "/usr/local/lib/python3.7/dist-packages/source_query_proxy/source/messages.py", line 130, in validate
    raise BrokenMessageError("Invalid value ({}) for field '{}'".format(value, self.name))
source_query_proxy.source.messages.BrokenMessageError: Invalid value (1918857325) for field 'split'

```
I get this error when I get UDP attack.

I have one file named: 00-globals.yaml in ./conf.d folder.

```
# Defaults for each server in `servers` section
# Any of these `values` can be overridden locally:
# in local `defaults` section
# in `servers` section
defaults:
  # True - defaults will be applied for each NEXT config file in conf.d directory
  # False - applied only for current file
  # conf.d/ files read sequentially by alphabetical order
  # we recommend start config names with sequential value: 00-globals.yaml, 01-game1.yaml, 02-game2.yaml
  global: True
  values:
    network:
      # Real game server IP address
      server_ip: '10.0.0.4'
      # IP address for listening incoming queries
      bind_ip: '0.0.0.0'
    # How often update A2S_INFO data
    a2s_info_cache_lifetime: 5
    # How often update A2S_RULES data
    a2s_rules_cache_lifetime: 5
    # How often update A2S_PLAYERS data
    a2s_players_cache_lifetime: 1
    # How often change src port for queries to Real Game Server
    # Some games required that due integrated ddos protection
    # Without it sqporxy ip:port will be "banned" for queries
    src_query_port_lifetime: 10


# See 01-dummy-game.yaml
servers:
  MyLittleServer:
    network:
      server_port: 27015
      bind_port: 27815

# Automatically run eBPF redirection
ebpf:
  # Download any release of SQProxy Kernel Module
  # And add path to `redirect.py`
  # https://github.com/spumer/source-query-proxy-kernel-module/releases
  enabled: False
  executable: 'python2'
  script_path: './src-ebpf/redirect.py'
```

Another question.
```
Do I need to create proxy server on bind port 27815 ?
```

Any problem here?

**Comment by spumer** [comment]
Looks like problem in invalid packets which ProxyServer received.
It's a bug, nice catch!

**Comment by abhishekdeshkar** [comment]
@spumer I'm on CS 1.6 server i.e HLDS. It doesn't work for HLDS packets. 

Currently using SourceQueryCacheMono but it is also not working against huge queries like 20k per second.

Attacker is using so many IPs to send UDP flood.

Anything I can do ?

Thanks!

**Comment by abhishekdeshkar** [comment]
@spumer Can I have multiple proxy servers while keeping 1 game server ?

So that incoming packets can be distributed across the different proxy servers.

**Comment by spumer** [comment]
sqproxy does not tested for HLDS (GoldSource).

----

Currently sqproxy can't bind multiple instances to same port to distribute incoming packets. 
SourceQueryCacheMono can't too i guess.

**Comment by abhishekdeshkar** [comment]
@spumer But will it work if we distribute incoming packets to multiple ports. Just a thought.

**Comment by spumer** [comment]
Distribute on single port (e.g. 27815) is possible. It's a small rework.
Distribute to multiple ports harder.
---

So. I investigate problem. HLDS (GoldSource) have different logic for splitting big packets. Currently it's not supported by sqproxy. But i think we can add support this in feature

**Comment by abhishekdeshkar** [comment]
@spumer  Can't you use same logic as ```SourceQueryCacheMono``` ? It works  with HLDS.

**Comment by spumer** [comment]
SourceQueryCacheMono only handle A2S_INFO packets. You can comment out code which send A2S_[PLAYERS, RULES] requests and disable redirection in eBPF script for that.

Then you got the same behaviour

**Comment by abhishekdeshkar** [comment]
@spumer I see. That's why it is not able to handle huge UDP flood. It is able to handle 5 million PPS attack but not able to handle 30 million PPS UDP flood :/

**Comment by spumer** [comment]
@abhishekdeshkar 
If you interesting in this project you can be sponsor. This help me implement critical features for you.

We can talk about your sitution in Discord: spumer#8462

**Comment by abhishekdeshkar** [comment]
@spumer I wish I could donate. :( Is there any good alternative ?

**Comment by spumer** [comment]
> @spumer I wish I could donate. :( Is there any good alternative ?

I don't know abotut that, this is why i start this project

**Comment by spumer** [comment]
I'm add new `no_a2s_rules` option to server config. See examples and changes in commit b8629bdda9b960eda570f6f24deb2a17fcff990a

But full support will be ready only after that: https://github.com/spumer/source-query-proxy/issues/21
