### ISSUE TITLE
No one server to run. Please check config

### ISSUE THREAD

**Issue by hznovich** [spumer/source-query-proxy#23]
Hi. Please help me figure out why it doesn’t work.
Ubuntu 20.04
bpfcc-tools 0.12
Installation of everything went without errors.

**/etc/sqproxy/conf.d/00-globals.yaml**
~~~
# Defaults for each server in 'servers' section
# Any of these 'values' can be overridden locally:
# in local 'defaults' section
# in 'servers' section
defaults:
  # True - defaults will be applied for each NEXT config file in conf.d directory
  # False - applied only for current file
  # conf.d/ files read sequentially by alphabetical order
  # we recommend start config names with sequential value: 00-globals.yaml, 01-game1.yaml, 02-game2.yaml
  global: True
  values:
    #network:
      # Real game server IP address
      #server_ip: '0.0.0.0'
      # IP address for listening incoming queries
      #bind_ip: '0.0.0.0'
    # How often update A2S_INFO data
    a2s_info_cache_lifetime: 5
    # How often update A2S_RULES data
    a2s_rules_cache_lifetime: 5
    # How often update A2S_PLAYERS data
    a2s_players_cache_lifetime: 1
    # How often change src port for queries to Real Game Server
    # Some games required that due integrated ddos protection
    # Without it sqporxy ip:port will be "banned" for queries
    src_query_port_lifetime: 10


# See 01-dummy-game.yaml
servers:

# Automatically run eBPF redirection
ebpf:
  # Download any release of SQProxy Kernel Module
  # And add path to 'redirect.py'
  # https://github.com/spumer/source-query-proxy-kernel-module/releases
  enabled: true
  executable: 'python3'
  script_path: '/etc/sqproxy/src-ebpf/redirect.py'
~~~
**/etc/sqproxy/conf.d/01-enp37s0f1.yaml**
~~~
# Local defaults
# Empty. Only demonstrate file structure
defaults:
    network:
      # Real game server IP address
      server_ip: '46.12.23.89'
      # IP address for listening incoming queries
      bind_ip: '46.12.23.89'

servers:
  100:
    network:
      server_port: 27029
      bind_port: 27829
  101:
    network:
      server_port: 27030
      bind_port: 27830
~~~
~~~
root@ubuntu:/# sqproxy run
2020-04-13 00:08:28,415 [WARNING] [sqproxy] No one server to run. Please check config
~~~
Why?
What am I doing wrong?

**Comment by spumer** [comment]
Any message about `Found config: /etc/sqproxy/conf.d/01-enp37s0f1.yaml` ?

**Comment by spumer** [comment]
I fix missing log messages in **1.0.1**. Now you should see more info in console when application started

**Comment by hznovich** [comment]
Hi.
~~~
root@ubuntu:/home/user# sqproxy run
2020-04-15 10:56:24,511 [DEBUG] [sqproxy.config] Sentry disabled
2020-04-15 10:56:24,511 [INFO] [sqproxy.config] Confdir not found: /etc/sqporxy/conf.d
2020-04-15 10:56:24,512 [INFO] [sqproxy.config] Confdir not found: /home/user/conf.d
2020-04-15 10:56:24,591 [WARNING] [sqproxy] No one server to run. Please check config
~~~
but... configs are present in /etc/sqporxy/conf.d. Re-checked several times.
I copied the configs here (/home/user/conf.d), then he sees them. But the following error after starting:
~~~
root@ubuntu:/etc/sqproxy# sqproxy run
2020-04-15 10:57:53,126 [DEBUG] [sqproxy.config] Sentry disabled
2020-04-15 10:57:53,126 [INFO] [sqproxy.config] Confdir not found: /etc/sqporxy/conf.d
2020-04-15 10:57:53,126 [INFO] [sqproxy.config] Found config: conf.d/00-globals.yaml
2020-04-15 10:57:53,128 [INFO] [sqproxy.config] Found config: conf.d/01-enp37s0f1.yaml
Traceback (most recent call last):
  File "/usr/local/bin/sqproxy", line 8, in <module>
    sys.exit(sqproxy())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/cli.py", line 12, in run
    from .__main__ import run
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/__main__.py", line 8, in <module>
    from . import config
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/config.py", line 194, in <module>
    setup(settings)
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/config.py", line 181, in setup
    servers = [(name, ServerModel.parse_obj(server)) for name, server in servers_.items()]
  File "/usr/local/lib/python3.8/dist-packages/source_query_proxy/config.py", line 181, in <listcomp>
    servers = [(name, ServerModel.parse_obj(server)) for name, server in servers_.items()]
  File "pydantic/main.py", line 402, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 283, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ServerModel
network -> server_ip
  field required (type=value_error.missing)
network -> bind_ip
  field required (type=value_error.missing)
~~~

**Comment by spumer** [comment]
Please post `ls -la /etc/sqproxy` output here

**Comment by spumer** [comment]
Lol. We have typo in default cfg: https://github.com/spumer/source-query-proxy/blob/master/source_query_proxy/config.py#L64

**Comment by hznovich** [comment]
~~~
root@ubuntu:/etc/sqproxy# ls -la /etc/sqproxy
total 16
drwxr-xr-x   4 root root 4096 Apr 12 16:22 .
drwxr-xr-x 100 root root 4096 Apr 12 16:14 ..
drwxr-xr-x   2 root root 4096 Apr 12 17:16 conf.d
drwxr-xr-x   2 root root 4096 Apr 12 16:21 src-ebpf
~~~

~~~
root@ubuntu:/etc/sqproxy/conf.d# ls -la /etc/sqproxy/conf.d/
total 16
drwxr-xr-x 2 root root 4096 Apr 12 17:16 .
drwxr-xr-x 4 root root 4096 Apr 12 16:22 ..
-rw-r--r-- 1 root root 1387 Apr 12 17:16 00-globals.yaml
-rw-r--r-- 1 root root  305 Apr 12 17:09 01-enp37s0f1.yaml
~~~

**Comment by spumer** [comment]
@hznovich you have invalid `defaults` section in `01-enp37s0f1.yaml`

You should put settings under `values` key, look at globals example

```yaml
defaults:
    values:
      network:
        # Real game server IP address
        server_ip: '46.12.23.89'
        # IP address for listening incoming queries
        bind_ip: '46.12.23.89'
```

**Comment by spumer** [comment]
I think now issue can be closed at all :)
